# PLEASE DO NOT EDIT 
# AUTOGENERATED WITH KUBEPAAS-GENERATOR

FROM {{ config.docker_image }}
WORKDIR /app
COPY package.json package-*.json ./
RUN npm i --only=production
COPY . .
CMD [ "npm", "run","start" ]