# PLEASE DO NOT EDIT 
# AUTOGENERATED WITH KUBEPAAS-GENERATOR

FROM {{config.docker_image}}
WORKDIR /app
COPY requirements.txt .
RUN pip install uwsgi==2.0.15 && pip install -r requirements.txt
COPY . .
CMD ["python","app.py"]